name: CI

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: python -m pip install -U pip
      - run: pip install -r requirements-core.txt -r requirements-client.txt -r requirements-dev.txt
      - run: pytest -q

  build-windows-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: python -m pip install -U pip
      - run: pip install -r requirements-core.txt -r requirements-client.txt -r requirements-dev.txt
      - name: Build EXEs
        shell: pwsh
        run: pwsh tools/build_win.ps1
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-exes
          path: dist/windows/**
